sudo: false

language: node_js
node_js:
  - 6
  - 8

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install coveralls
  - git config --global user.email "jonathan.buchanan@gmail.com"
  - git config --global user.name "Jonny Buchanan"

script: "npm run test:coverage"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - next
    - webpack4
    - babel7
